# Generated by Django 3.1.6 on 2021-03-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0005_auto_20210315_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndikatorPlotKonfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von_datum', models.DateField()),
                ('bis_datum', models.DateField()),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
